# Generated by Django 5.1.1 on 2025-12-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('lost', 'Perdido'), ('dating', 'Busca pareja'), ('transit', 'Disponible para tránsito')], default='normal', max_length=10),
        ),
    ]
