# Generated by Django 5.1.1 on 2026-01-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='url',
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('feed', 'Feed (posteo)'), ('sidebar', 'Sidebar')], default='feed', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ad',
            name='zones',
            field=models.ManyToManyField(blank=True, to='ads.zone'),
        ),
    ]
