# Generated by Django 5.1.1 on 2026-01-04 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useropinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useropinion',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='useropinion',
            name='target_user',
        ),
        migrations.AddField(
            model_name='useropinion',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='useropinion',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='useropinion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_opinions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useropinion',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='useropinion',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AddConstraint(
            model_name='useropinion',
            constraint=models.UniqueConstraint(fields=('profile', 'author'), name='one_opinion_per_user_per_profile'),
        ),
    ]
