# Generated by Django 5.1.1 on 2026-01-25 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_useropinion_is_active_and_more'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.zone'),
        ),
    ]
