# Generated by Django 5.1.1 on 2025-12-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfoundpost',
            name='animal_other',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lostfoundpost',
            name='pattern',
            field=models.CharField(choices=[('liso', 'Liso'), ('manchas', 'Manchas'), ('rayas', 'Rayas')], default='liso', max_length=20),
        ),
        migrations.AlterField(
            model_name='lostfoundpost',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('bird', 'Pájaro'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lostfoundpost',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lostfoundpost',
            name='size',
            field=models.CharField(choices=[('xs', 'Muy chico'), ('s', 'Chico'), ('m', 'Mediano'), ('l', 'Grande'), ('xl', 'Muy grande')], max_length=5),
        ),
    ]
