# Generated by Django 5.1.1 on 2026-01-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0002_lostfoundpost_animal_other_lostfoundpost_pattern_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostfoundpost',
            old_name='created_at',
            new_name='created',
        ),
    ]
