# Generated by Django 5.1.1 on 2026-01-18 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_cover_alter_group_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['joined_at']},
        ),
        migrations.AlterModelOptions(
            name='grouppost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
