# Generated by Django 5.1.1 on 2026-01-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members_public',
            field=models.BooleanField(default=True),
        ),
    ]
