# Generated by Django 5.1.1 on 2026-01-09 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FosterAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_adult', models.BooleanField(verbose_name='Soy mayor de 18 años')),
                ('animal_type', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('other', 'Otro')], max_length=20)),
                ('animal_other', models.CharField(blank=True, max_length=50)),
                ('health_condition', models.CharField(choices=[('healthy', 'Sano'), ('injured', 'Herido'), ('sick', 'Enfermo'), ('Quelquechose', 'sin preferencias')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Espacio disponible, experiencia, condiciones, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foster_availability', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
