# Generated by Django 5.1.1 on 2026-01-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosteravailability',
            name='health_condition',
            field=models.CharField(choices=[('healthy', 'Sano'), ('injured', 'Herido'), ('sick', 'Enfermo'), ('Quelquechose', 'sin preferencias')], max_length=20),
        ),
    ]
