# Generated by Django 5.1.1 on 2026-01-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('message', 'Message'), ('post', 'Post'), ('pet', 'Mascota'), ('group', 'Group'), ('store', 'Store'), ('system', 'System')], max_length=30),
        ),
    ]
