# Generated by Django 5.1.1 on 2025-12-21 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParroquialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('service_type', models.CharField(choices=[('vet', 'Veterinaria'), ('grooming', 'Peluquería'), ('walker', 'Paseadores'), ('discounts', 'Descuentos'), ('food', 'Alimentos'), ('clinic', 'Clínicas'), ('other', 'Otro')], max_length=20)),
                ('zone', models.CharField(help_text='Barrio o zona principal', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquial_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
