# Generated by Django 5.1.1 on 2025-12-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parroquiales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parroquialpost',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='parroquialpost',
            name='service_type',
            field=models.CharField(choices=[('vet', 'Veterinaria'), ('grooming', 'Peluquería'), ('walker', 'Paseadores'), ('discounts', 'Descuentos'), ('food', 'Alimentos'), ('clinics', 'Clínicas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parroquialpost',
            name='zone',
            field=models.CharField(max_length=120),
        ),
    ]
